version: '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - dbvol:/var/lib/mysql

     environment:
       MYSQL_ROOT_PASSWORD: quotysco
       MYSQL_DATABASE: quotysco
       MYSQL_USER: quotysco
       MYSQL_PASSWORD: quotysco

   quotysco:
     depends_on:
       - db
     image: interaapps/quotysco:latest
     ports:
       - "9999:80"
       
     environment:
       HTTP_SERVER_PORT: 80
       HTTP_SERVER_CORS: "*"
       DATABASE_DRIVER: mysql
       DATABASE_NAME: quotysco
       DATABASE_USER: quotysco
       DATABASE_PASSWORD: quotysco
       DATABASE_HOST: db
       DATABASE_PORT: 3306
       SERVER_NAME: "http://localhost:9999"
       IA_OAUTH2_CLIENT_ID:
       IA_OAUTH2_CLIENT_SECRET:
 
       FTP_URL:
       FTP_HOST:
       FTP_USER:
       FTP_PASSWORD:
       FTP_BASE_DIR:

volumes:
  dbvol: